############################################
# Class to hold the non-changing data sets
# that will be used in the program.
############################################

class Immutable:
	# Dictionary to store all of the codons for each of the amino acids (U replaced with T for simplicity)
	amino_acid_codons = {
		"A": ["GCT", "GCC", "GCA", "GCG"],
		"R": ["CGT", "CGC", "CGA", "CGG", "AGA", "AGG"],
		"N": ["AAT", "AAC"],
		"D": ["GAT", "GAC"],
		# Add 'B' asparagine OR aspartic acid for ambiguity
		"C": ["TGT", "TGC"],
		"Q": ["CAA", "CAG"],
		"E": ["GAA", "GAG"],
		# Add 'Z' glutamine OR glutamic acid for ambiguity
		"G": ["GGT", "GGC", "GGA", "GGG"],
		"H": ["CAT", "CAC"],
		"I": ["ATT", "ATC", "ATA"],
		"L": ["TTA", "TTG", "CTT", "CTC", "CTA", "CTG"],
		"K": ["AAA", "AAG"],
		"M": ["ATG",],
		"F": ["TTT", "TTC"],
		"P": ["CCT", "CCC", "CCA", "CCG"],
		"S": ["TCT", "TCC", "TCA", "TCG", "AGT", "AGC"],
		"T": ["ACT", "ACC", "ACA", "ACG"],
		"W": ["TGG",],
		"Y": ["TAT", "TAC"],
		"V": ["GTT", "GTC", "GTA", "GTG"],
		"stop": ["TAA", "TAG", "TGA"]
	}
	# Dictionary to store all bases that correspond to symbols which represent ambiguity
	ambiguity = {
		"G": ["G"],
		"C": ["C"],
		"A": ["A"],
		"T": ["T"],
		"R": ["G", "A"],
		"Y": ["C", "T"],
		"M": ["A", "C"],
	 	"K": ["G", "T"],
		"S": ["G", "C"],
		"W": ["A", "T"],
		"B": ["C", "G", "T"],
		"D": ["A", "G", "T"],
		"H": ["A", "C", "T"],
		"V": ["A", "C", "G"],
		"N": ["N"]
	}
	mod_enz_seqs = {
		"AclI": "AACGTT",
		"HindIII": "AAGCTT",
		"HindIII-HF®": "AAGCTT",
		"SspI": "AATATT",
		"SspI-HF®": "AATATT",
		"MluCI": "AATT",
		"PciI": "ACATGT",
		"AgeI": "ACCGGT",
		"AgeI-HF®": "ACCGGT",
		"BspMI": "ACCTGC",
		"BfuAI": "ACCTGC",
		"SexAI": "ACCWGGT",
		"MluI": "ACGCGT",
		"MluI-HF®": "ACGCGT",
		"BceAI": "ACGGC",
		"HpyCH4IV": "ACGT",
		"HpyCH4III": "ACNGT",
		"BaeI": "ACNNNNGTAYC",
		"BsaXI": "ACNNNNNCTCC",
		"AflIII": "ACRYGT",
		"SpeI": "ACTAGT",
		"SpeI-HF®": "ACTAGT",
		"BsrI": "ACTGG",
		"BmrI": "ACTGGG",
		"BglII": "AGATCT",
		"AfeI": "AGCGCT",
		"AluI": "AGCT",
		"StuI": "AGGCCT",
		"ScaI-HF®": "AGTACT",
		"BspDI": "ATCGAT",
		"ClaI": "ATCGAT",
		"PI-SceI": "ATCTATGTCGGGTGCGGAGAAAGAGGTAAT",
		"NsiI": "ATGCAT",
		"NsiI-HF®": "ATGCAT",
		"AseI": "ATTAAT",
		"SwaI": "ATTTAAAT",
		"CspCI": "CAANNNNNGTGG",
		"MfeI": "CAATTG",
		"MfeI-HF®": "CAATTG",
		"Nb.BssSI": "CACGAG",
		"BssSI-v2": "CACGAG",
		"BmgBI": "CACGTC",
		"PmlI": "CACGTG",
		"DraIII-HF®": "CACNNNGTG",
		"AleI-v2": "CACNNNNGTG",
		"EcoP15I": "CAGCAG",
		"PvuII": "CAGCTG",
		"PvuII-HF®": "CAGCTG",
		"AlwNI": "CAGNNNCTG",
		"BtsIMutI": "CAGTG",
		"NdeI": "CATATG",
		"CviAII": "CATG",
		"FatI": "CATG",
		"NlaIII": "CATG",
		"MslI": "CAYNNNNRTG",
		"FspEI": "CC",
		"XcmI": "CCANNNNNNNNNTGG",
		"BstXI": "CCANNNNNNTGG",
		"PflMI": "CCANNNNNTGG",
		"BccI": "CCATC",
		"NcoI-HF®": "CCATGG",
		"NcoI": "CCATGG",
		"BseYI": "CCCAGC",
		"FauI": "CCCGC",
		"XmaI": "CCCGGG",
		"TspMI": "CCCGGG",
		"SmaI": "CCCGGG",
		"Nt.CviPII": "CCD",
		"LpnPI": "CCDG",
		"AciI": "CCGC",
		"SacII": "CCGCGG",
		"BsrBI": "CCGCTC",
		"HpaII": "CCGG",
		"MspI": "CCGG",
		"ScrFI": "CCNGG",
		"StyD4I": "CCNGG",
		"BsaJI": "CCNNGG",
		"BslI": "CCNNNNNNNGG",
		"BtgI": "CCRYGG",
		"NciI": "CCSGG",
		"AvrII": "CCTAGG",
		"MnlI": "CCTC",
		"BbvCI": "CCTCAGC",
		"Nt.BbvCI": "CCTCAGC",
		"Nb.BbvCI": "CCTCAGC",
		"SbfI": "CCTGCAGG",
		"SbfI-HF®": "CCTGCAGG",
		"Bpu10I": "CCTNAGC",
		"Bsu36I": "CCTNAGG",
		"EcoNI": "CCTNNNNNAGG",
		"HpyAV": "CCTTC",
		"BstNI": "CCWGG",
		"PspGI": "CCWGG",
		"StyI-HF®": "CCWWGG",
		"StyI": "CCWWGG",
		"BcgI": "CGANNNNNNTGC",
		"PvuI": "CGATCG",
		"PvuI-HF®": "CGATCG",
		"BstUI": "CGCG",
		"EagI-HF®": "CGGCCG",
		"EagI": "CGGCCG",
		"RsrII": "CGGWCCG",
		"BsiEI": "CGRYCG",
		"None": "GTATAC",
		"BsiWI": "CGTACG",
		"Esp3I": "CGTCTC",
		"BsmBI": "CGTCTC",
		"Hpy99I": "CGWCG",
		"MspA1I": "CMGCKG",
		"AbaSI": "CNNNNNNNNNNNNNNNNNNNNG",
		"MspJI": "CNNR",
		"SgrAI": "CRCCGGYG",
		"BfaI": "CTAG",
		"BspCNI": "CTCAG",
		"PaeR7I": "CTCGAG",
		"XhoI": "CTCGAG",
		"EarI": "CTCTTC",
		"AcuI": "CTGAAG",
		"PstI-HF®": "CTGCAG",
		"PstI": "CTGCAG",
		"BpmI": "CTGGAG",
		"DdeI": "CTNAG",
		"SfcI": "CTRYAG",
		"AflII": "CTTAAG",
		"BpuEI": "CTTGAG",
		"SmlI": "CTYRAG",
		"BsoBI": "CYCGRG",
		"AvaI": "CYCGRG",
		"MboII": "GAAGA",
		"BbsI": "GAAGAC",
		"XmnI": "GAANNNNTTC",
		"BsmI": "GAATGC",
		"Nb.BsmI": "GAATGC",
		"EcoRI-HF®": "GAATTC",
		"EcoRI": "GAATTC",
		"HgaI": "GACGC",
		"ZraI": "GACGTC",
		"AatII": "GACGTC",
		"PflFI": "GACNNNGTC",
		"Tth111I": "GACNNNGTC",
		"PshAI": "GACNNNNGTC",
		"AhdI": "GACNNNNNGTC",
		"DrdI": "GACNNNNNNGTC",
		"Eco53kI": "GAGCTC",
		"SacI": "GAGCTC",
		"SacI-HF®": "GAGCTC",
		"BseRI": "GAGGAG",
		"PleI": "GAGTC",
		"Nt.BstNBI": "GAGTC",
		"MlyI": "GAGTC",
		"HinfI": "GANTC",
		"EcoRV-HF®": "GATATC",
		"EcoRV": "GATATC",
		"DpnI": "GATC",
		"MboI": "GATC",
		"DpnII": "GATC",
		"Sau3AI": "GATC",
		"BsaBI": "GATNNNNATC",
		"TfiI": "GAWTC",
		"Nb.BsrDI": "GCAATG",
		"BsrDI": "GCAATG",
		"BbvI": "GCAGC",
		"Nb.BtsI": "GCAGTG",
		"BtsI-v2": "GCAGTG",
		"BstAPI": "GCANNNNNTGC",
		"SfaNI": "GCATC",
		"SphI": "GCATGC",
		"SphI-HF®": "GCATGC",
		"SrfI": "GCCCGGGC",
		"NmeAIII": "GCCGAG",
		"NgoMIV": "GCCGGC",
		"NaeI": "GCCGGC",
		"BglI": "GCCNNNNNGGC",
		"AsiSI": "GCGATCGC",
		"BtgZI": "GCGATG",
		"HinP1I": "GCGC",
		"HhaI": "GCGC",
		"BssHII": "GCGCGC",
		"NotI": "GCGGCCGC",
		"NotI-HF®": "GCGGCCGC",
		"Fnu4HI": "GCNGC",
		"Cac8I": "GCNNGC",
		"MwoI": "GCNNNNNNNGC",
		"NheI": "GCTAGC",
		"NheI-HF®": "GCTAGC",
		"BmtI-HF®": "GCTAGC",
		"BmtI": "GCTAGC",
		"BspQI": "GCTCTTC",
		"SapI": "GCTCTTC",
		"Nt.BspQI": "GCTCTTC",
		"BlpI": "GCTNAGC",
		"ApeKI": "GCWGC",
		"TseI": "GCWGC",
		"Bsp1286I": "GDGCHC",
		"Nt.AlwI": "GGATC",
		"AlwI": "GGATC",
		"BamHI-HF®": "GGATCC",
		"BamHI": "GGATCC",
		"BtsCI": "GGATG",
		"FokI": "GGATG",
		"HaeIII": "GGCC",
		"FseI": "GGCCGGCC",
		"SfiI": "GGCCNNNNNGGCC",
		"SfoI": "GGCGCC",
		"PluTI": "GGCGCC",
		"NarI": "GGCGCC",
		"KasI": "GGCGCC",
		"AscI": "GGCGCGCC",
		"EciI": "GGCGGA",
		"BsmFI": "GGGAC",
		"ApaI": "GGGCCC",
		"PspOMI": "GGGCCC",
		"Sau96I": "GGNCC",
		"NlaIV": "GGNNCC",
		"KpnI-HF®": "GGTACC",
		"KpnI": "GGTACC",
		"Acc65I": "GGTACC",
		"BsaI": "GGTCTC",
		"BsaI-HF®v2": "GGTCTC",
		"HphI": "GGTGA",
		"BstEII-HF®": "GGTNACC",
		"BstEII ": "GGTNACC",
		"AvaII": "GGWCC",
		"BanI": "GGYRCC",
		"BaeGI": "GKGCMC",
		"BsaHI": "GRCGYC",
		"BanII": "GRGCYC",
		"RsaI": "GTAC",
		"CviQI": "GTAC",
		"BciVI": "GTATCC",
		"SalI-HF®": "GTCGAC",
		"SalI": "GTCGAC",
		"Nt.BsmAI": "GTCTC",
		"BcoDI": "GTCTC",
		"BsmAI": "GTCTC",
		"ApaLI": "GTGCAC",
		"BsgI": "GTGCAG",
		"AccI": "GTMKAC",
		"Hpy166II": "GTNNAC",
		"Tsp45I": "GTSAC",
		"HpaI": "GTTAAC",
		"PmeI": "GTTTAAAC",
		"HincII": "GTYRAC",
		"BsiHKAI": "GWGCWC",
		"TspRI": "NNCASTGNN",
		"ApoI": "RAATTY",
		"ApoI-HF": "RAATTY",
		"NspI": "RCATGY",
		"BsrFI-v2": "RCCGGY",
		"BstYI": "RGATCY",
		"HaeII": "RGCGCY",
		"CviKI-1": "RGCY",
		"EcoO109I": "RGGNCCY",
		"PpuMI": "RGGWCCY",
		"I-CeuI": "TAACTATAACGGTCCTAAGGTAGCGAA",
		"SnaBI": "TACGTA",
		"I-SceI": "TAGGGATAACAGGGTAAT",
		"BspHI": "TCATGA",
		"BspEI": "TCCGGA",
		"MmeI": "TCCRAC",
		"TaqI-v2": "TCGA",
		"NruI": "TCGCGA",
		"NruI-HF®": "TCGCGA",
		"Hpy188I": "TCNGA",
		"Hpy188III": "TCNNGA",
		"XbaI": "TCTAGA",
		"BclI": "TGATCA",
		"BclI-HF": "TGATCA",
		"HpyCH4V": "TGCA",
		"FspI": "TGCGCA",
		"PI-PspI": "TGGCAAACAGCTATTATGGGTATTATGGGT",
		"MscI": "TGGCCA",
		"BsrGI": "TGTACA",
		"BsrGI-HF®": "TGTACA",
		"MseI": "TTAA",
		"PacI": "TTAATTAA",
		"PsiI-v2": "TTATAA",
		"BstBI": "TTCGAA",
		"DraI": "TTTAAA",
		"PspXI": "VCTCGAGB",
		"BsaWI": "WCCGGW",
		"BsaAI": "YACGTR",
		"EaeI": "YGGCCR"
	}